version: "3.9"
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver2019
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_volume:/var/opt/mssql
      - "D:/docker-compose/public:/var/mypubl"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Developer
  redis:
    container_name: redis
    hostname: redis
    image: "redis:6.2"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  sqlserver_volume:
  redis:
    driver: local